import io
import json
import tempfile
import unittest
from contextlib import redirect_stdout
from pathlib import Path

import scripts.export_latex_tables as export


class ExportLatexTablesTest(unittest.TestCase):
    def test_qed_table_exports_complete_quality_gate_rows(self):
        with tempfile.TemporaryDirectory() as tmp:
            old_out_dir = export.OUT_DIR
            try:
                export.OUT_DIR = Path(tmp)
                rows = [
                    {
                        "root": "final",
                        "manifest_group": "",
                        "variant": "A8",
                        "condition": "qed",
                        "status": "complete_pass",
                        "alpha": "alpha=5.0",
                        "spearman_rho": "0.50997",
                        "slope": "0.8279",
                        "uniqueness": "0.7408",
                        "mae": "0.19435",
                    },
                    {
                        "root": "final",
                        "manifest_group": "",
                        "variant": "A6",
                        "condition": "qed",
                        "status": "pending",
                        "alpha": "",
                        "spearman_rho": "",
                        "uniqueness": "",
                        "mae": "",
                    },
                ]
                with redirect_stdout(io.StringIO()):
                    export.qed_table(rows)
            finally:
                export.OUT_DIR = old_out_dir

            text = (Path(tmp) / "tab_qed_main.tex").read_text()
            self.assertIn("% Generated by scripts/export_latex_tables.py", text)
            self.assertIn("Decoder coupling (no diversity) & 5.0 & 0.510 & 0.828 & 74.1 & 0.194", text)
            self.assertNotIn("Single-$\\tau$ decoder drift", text)

    def test_qed_table_ignores_publication_seed_replicates(self):
        with tempfile.TemporaryDirectory() as tmp:
            old_out_dir = export.OUT_DIR
            try:
                export.OUT_DIR = Path(tmp)
                rows = [
                    {
                        "root": "final",
                        "manifest_group": "",
                        "variant": "F",
                        "condition": "qed",
                        "status": "complete_pass",
                        "alpha": "alpha=5.0",
                        "spearman_rho": "0.49337",
                        "slope": "0.7955",
                        "uniqueness": "0.9465",
                        "mae": "0.200",
                    },
                    {
                        "root": "seeds",
                        "manifest_group": "qed_3seed",
                        "variant": "F",
                        "condition": "qed",
                        "status": "complete_pass",
                        "alpha": "alpha=5.0",
                        "spearman_rho": "0.52361",
                        "slope": "0.8526",
                        "uniqueness": "0.9429",
                        "mae": "0.209",
                    },
                ]
                with redirect_stdout(io.StringIO()):
                    export.qed_table(rows)
            finally:
                export.OUT_DIR = old_out_dir

            text = (Path(tmp) / "tab_qed_main.tex").read_text()
            self.assertIn("\\textbf{DriftingMol} & 5.0 & 0.493 & 0.795 & 94.7 & 0.200", text)
            self.assertNotIn("0.524", text)

    def test_multi4_table_uses_only_fair_v2_rows(self):
        with tempfile.TemporaryDirectory() as tmp:
            old_out_dir = export.OUT_DIR
            try:
                export.OUT_DIR = Path(tmp)
                rows = [
                    {
                        "root": "final",
                        "variant": "A6",
                        "condition": "multi4",
                        "status": "complete_pass",
                        "alpha": "alpha=3.0",
                        "qed_rho": "0.1",
                        "sa_score_rho": "0.1",
                        "logp_rho": "0.1",
                        "molwt_rho": "0.1",
                        "avg_spearman_rho": "0.1",
                    },
                    {
                        "root": "final_v2",
                        "variant": "A6",
                        "condition": "multi4",
                        "status": "complete_pass",
                        "alpha": "alpha=5.0",
                        "qed_rho": "0.3667",
                        "sa_score_rho": "0.5290",
                        "logp_rho": "0.7082",
                        "molwt_rho": "0.7900",
                        "avg_spearman_rho": "0.5985",
                        "min_uniqueness": "0.8819",
                    },
                ]
                with redirect_stdout(io.StringIO()):
                    export.multi4_table(rows)
            finally:
                export.OUT_DIR = old_out_dir

            text = (Path(tmp) / "tab_multi4_v2.tex").read_text()
            self.assertIn("Decoder coupling (single $\\tau$) & 5.0 & 0.367 & 0.529 & 0.708 & 0.790 & 0.599 & 88.2", text)
            self.assertNotIn("& 3.0 & 0.100", text)

    def test_qed_seed_table_formats_missing_ci(self):
        with tempfile.TemporaryDirectory() as tmp:
            tmp_path = Path(tmp)
            status = tmp_path / "publication_status.json"
            status.write_text(
                json.dumps(
                    {
                        "qed_3seed": [
                            {
                                "variant": "A6",
                                "seeds": "42,43,44",
                                "n": 3,
                                "rho_mean": 0.50,
                                "rho_ci95": 0.01234,
                            },
                            {
                                "variant": "G4",
                                "seeds": "42",
                                "n": 1,
                                "rho_mean": 0.44,
                                "rho_ci95": None,
                            },
                        ]
                    }
                )
            )
            old_out_dir, old_status = export.OUT_DIR, export.STATUS_JSON
            try:
                export.OUT_DIR = tmp_path
                export.STATUS_JSON = status
                with redirect_stdout(io.StringIO()):
                    export.qed_seed_table()
            finally:
                export.OUT_DIR = old_out_dir
                export.STATUS_JSON = old_status

            text = (tmp_path / "tab_qed_3seed.tex").read_text()
            self.assertIn("Decoder coupling (single $\\tau$) & 42,43,44 & 3 & 0.500 & 0.012", text)
            self.assertIn("Layer-balanced decoder coupling & 42 & 1 & 0.440 & ---", text)


if __name__ == "__main__":
    unittest.main()
