#!/usr/bin/env python3
"""Collect VAE sensitivity runs from the extension manifest."""
from __future__ import annotations

import csv
import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "configs" / "publication_ext" / "manifest.json"
OUT_CSV = ROOT / "results" / "vae_sensitivity.csv"
OUT_STATUS = ROOT / "results" / "vae_sensitivity_status.json"
OUT_TEX = ROOT / "results" / "tables" / "tab_vae_sensitivity.tex"


DISPLAY_NAMES = {
    "V_BETA_LOW": "Low beta",
    "V_BETA_HIGH": "High beta",
    "V_LATENT128": "Latent-128",
    "V_DEC6": "Decoder-6",
}


def load_json(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text())
    except json.JSONDecodeError:
        return {}


def fnum(value: Any, digits: int = 3) -> str:
    if value in (None, "", "-"):
        return "---"
    try:
        return f"{float(value):.{digits}f}"
    except (TypeError, ValueError):
        return str(value)


def fpct(value: Any, digits: int = 1) -> str:
    if value in (None, "", "-"):
        return "---"
    try:
        return f"{100.0 * float(value):.{digits}f}"
    except (TypeError, ValueError):
        return str(value)


def parse_variant(name: str) -> str:
    if not name.startswith("ext_") or "_vae_" not in name:
        return name
    return name[len("ext_") : name.index("_vae_")]


def row_for_entry(entry: dict[str, Any]) -> dict[str, Any]:
    name = entry["name"]
    variant = parse_variant(name)
    metrics_path = ROOT / entry["output_dir"] / "final_metrics.json"
    metrics = load_json(metrics_path)
    status = "complete_pass" if metrics else "pending"
    return {
        "status": status,
        "experiment": name,
        "variant": variant,
        "display": DISPLAY_NAMES.get(variant, variant),
        "purpose": entry.get("purpose", ""),
        "exact_recon": metrics.get("exact_recon"),
        "token_acc": metrics.get("token_acc"),
        "prior_validity": metrics.get("prior_validity"),
        "prior_uniqueness": metrics.get("prior_uniqueness"),
        "prior_novelty": metrics.get("prior_novelty"),
        "prior_vun": metrics.get("prior_vun"),
        "output_dir": entry["output_dir"],
        "config": entry.get("config", ""),
        "command": entry.get("command", ""),
    }


def parallel_running_names() -> set[str]:
    names: set[str] = set()
    for path in (ROOT / "outputs" / "publication_ext").glob("parallel_runner_status*.json"):
        payload = load_json(path)
        if payload.get("state") != "running":
            continue
        for item in payload.get("running", []):
            name = item.get("name")
            if name:
                names.add(str(name))
    return names


def write_csv(rows: list[dict[str, Any]]) -> None:
    OUT_CSV.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = [
        "status",
        "experiment",
        "variant",
        "display",
        "purpose",
        "exact_recon",
        "token_acc",
        "prior_validity",
        "prior_uniqueness",
        "prior_novelty",
        "prior_vun",
        "output_dir",
        "config",
        "command",
    ]
    with OUT_CSV.open("w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames, lineterminator="\n")
        writer.writeheader()
        writer.writerows(rows)


def write_status(rows: list[dict[str, Any]]) -> None:
    complete = [row for row in rows if str(row["status"]).startswith("complete")]
    pending = [row for row in rows if not str(row["status"]).startswith("complete")]
    OUT_STATUS.write_text(
        json.dumps(
            {
                "num_experiments": len(rows),
                "complete": len(complete),
                "pending_or_incomplete": len(pending),
                "minimum_completed_runs_for_sensitivity": 1,
                "minimum_completed_runs_reached": len(complete) >= 1,
                "pending_or_incomplete_entries": pending,
            },
            indent=2,
        )
        + "\n"
    )


def write_tex(rows: list[dict[str, Any]]) -> None:
    OUT_TEX.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "% Generated by scripts/collect_vae_sensitivity.py",
        "\\begin{tabular}{l c c c c c}",
        "\\toprule",
        "VAE variant & Status & Exact recon (\\%) & Prior V (\\%) & Prior U (\\%) & Prior VUN \\\\",
        "\\midrule",
    ]
    for row in rows:
        status = str(row["status"]).replace("_", "\\_")
        lines.append(
            f"{row['display']} & {status} & "
            f"{fpct(row.get('exact_recon'))} & {fpct(row.get('prior_validity'))} & "
            f"{fpct(row.get('prior_uniqueness'))} & {fnum(row.get('prior_vun'))} \\\\"
        )
    lines += ["\\bottomrule", "\\end{tabular}"]
    OUT_TEX.write_text("\n".join(lines) + "\n")


def main() -> None:
    manifest = load_json(MANIFEST)
    entries = [entry for entry in manifest.get("entries", []) if entry.get("group") == "vae_sensitivity"]
    rows = [row_for_entry(entry) for entry in entries]
    running = parallel_running_names()
    for row in rows:
        if row["experiment"] in running and row["status"] == "pending":
            row["status"] = "running_or_incomplete"
    rows.sort(key=lambda row: row["experiment"])
    write_csv(rows)
    write_status(rows)
    write_tex(rows)
    print(f"Collected {len(rows)} VAE sensitivity entries")
    print(f"Wrote {OUT_CSV.relative_to(ROOT)}")
    print(f"Wrote {OUT_STATUS.relative_to(ROOT)}")
    print(f"Wrote {OUT_TEX.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
