#!/usr/bin/env python3
"""Collect live, non-final VAE-drift progress from training logs.

This is a monitoring artifact only. Final claims must still use
`final_metrics.json` collected by `collect_vae_drift_results.py`.
"""
from __future__ import annotations

import argparse
import json
import math
import re
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_MANIFEST = ROOT / "configs" / "publication_ext" / "vae_drift_manifest.json"
DEFAULT_LOG_DIR = ROOT / "outputs" / "publication_ext" / "vae_drift_logs"
OUT_JSON = ROOT / "results" / "vae_drift_live_snapshot.json"
OUT_TEX = ROOT / "results" / "tables" / "tab_vae_drift_live_snapshot.tex"

RHO = "\u03c1"
EVAL_RE = re.compile(
    r"\[epoch\s+(?P<epoch>\d+)\].*"
    r"V=(?P<validity>[0-9.]+)%\s+"
    r"U=(?P<uniqueness>[0-9.]+)%\s+"
    r"N=(?P<novelty>[0-9.]+)%\s+"
    + re.escape(RHO)
    + r"=(?P<rho>-?[0-9.]+)\s+"
    r"MAE=(?P<mae>[0-9.]+)\s+"
    r"slope=(?P<slope>-?[0-9.]+)"
)
GATE_RE = re.compile(r"Gate=(?P<gate>[A-Z]+)")


def read_json(path: Path) -> dict[str, Any]:
    try:
        return json.loads(path.read_text())
    except Exception:
        return {}


def manifest_entries(path: Path) -> list[dict[str, Any]]:
    payload = read_json(path)
    entries = payload.get("entries", [])
    return entries if isinstance(entries, list) else []


def parse_float(value: str) -> float:
    try:
        return float(value)
    except ValueError:
        return math.nan


def parse_log(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {"exists": False, "evals": [], "last_eval": None, "best_eval": None}
    evals: list[dict[str, Any]] = []
    last_eval: dict[str, Any] | None = None
    for line in path.read_text(errors="replace").splitlines():
        match = EVAL_RE.search(line)
        if match:
            item = {
                "epoch": int(match.group("epoch")),
                "validity": parse_float(match.group("validity")) / 100.0,
                "uniqueness": parse_float(match.group("uniqueness")) / 100.0,
                "novelty": parse_float(match.group("novelty")) / 100.0,
                "spearman_rho": parse_float(match.group("rho")),
                "mae": parse_float(match.group("mae")),
                "slope": parse_float(match.group("slope")),
                "gate": "",
            }
            evals.append(item)
            last_eval = item
            continue
        gate = GATE_RE.search(line)
        if gate and last_eval is not None and not last_eval.get("gate"):
            last_eval["gate"] = gate.group("gate")
    best_eval = None
    if evals:
        best_eval = max(
            evals,
            key=lambda item: (
                item.get("gate") == "PASS",
                item.get("spearman_rho", -999.0),
                item.get("uniqueness", 0.0),
            ),
        )
    return {
        "exists": True,
        "num_evals": len(evals),
        "last_eval": evals[-1] if evals else None,
        "best_eval": best_eval,
    }


def fmt(value: Any, digits: int = 3) -> str:
    if value is None:
        return "---"
    try:
        val = float(value)
    except (TypeError, ValueError):
        return str(value)
    if math.isnan(val):
        return "---"
    return f"{val:.{digits}f}"


def pct(value: Any, digits: int = 1) -> str:
    if value is None:
        return "---"
    try:
        val = 100.0 * float(value)
    except (TypeError, ValueError):
        return str(value)
    if math.isnan(val):
        return "---"
    return f"{val:.{digits}f}"


def build_snapshot(manifest_path: Path, log_dir: Path) -> dict[str, Any]:
    rows = []
    for entry in manifest_entries(manifest_path):
        name = str(entry.get("name", ""))
        parsed = parse_log(log_dir / f"{name}.log")
        rows.append(
            {
                "experiment": name,
                "display": entry.get("display", name),
                "purpose": entry.get("purpose", ""),
                "output_dir": entry.get("output_dir", ""),
                "log": str((log_dir / f"{name}.log").relative_to(ROOT)),
                **parsed,
            }
        )
    return {
        "note": "Live snapshot parsed from logs; use final_metrics.json for paper claims.",
        "num_experiments": len(rows),
        "rows": rows,
    }


def write_tex(path: Path, snapshot: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "% Generated by scripts/collect_vae_drift_live_snapshot.py",
        "% Live monitoring only; not final paper evidence.",
        "\\begin{tabular}{l c c c c c c}",
        "\\toprule",
        "Run & Last epoch & Last $\\rho$ & Best epoch & Best $\\rho$ & Best U (\\%) & Gate \\\\",
        "\\midrule",
    ]
    for row in snapshot["rows"]:
        last = row.get("last_eval") or {}
        best = row.get("best_eval") or {}
        name = row["experiment"].replace("_", "\\_")
        lines.append(
            f"{name} & "
            f"{last.get('epoch', '---')} & {fmt(last.get('spearman_rho'))} & "
            f"{best.get('epoch', '---')} & {fmt(best.get('spearman_rho'))} & "
            f"{pct(best.get('uniqueness'))} & {best.get('gate') or '---'} \\\\"
        )
    lines += ["\\bottomrule", "\\end{tabular}"]
    path.write_text("\n".join(lines) + "\n")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", default=str(DEFAULT_MANIFEST))
    parser.add_argument("--log-dir", default=str(DEFAULT_LOG_DIR))
    args = parser.parse_args()

    manifest_path = Path(args.manifest)
    if not manifest_path.is_absolute():
        manifest_path = ROOT / manifest_path
    log_dir = Path(args.log_dir)
    if not log_dir.is_absolute():
        log_dir = ROOT / log_dir

    snapshot = build_snapshot(manifest_path, log_dir)
    OUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    OUT_JSON.write_text(json.dumps(snapshot, indent=2) + "\n")
    write_tex(OUT_TEX, snapshot)
    print(f"Wrote {OUT_JSON.relative_to(ROOT)}")
    print(f"Wrote {OUT_TEX.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
