#!/usr/bin/env python3
"""Export publication result CSVs to LaTeX table snippets.

The snippets are generated artifacts under `results/tables/` and are intended
to keep manuscript tables synchronized with `scripts/collect_results.py`.
"""
from __future__ import annotations

import csv
import json
import math
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
RESULTS_CSV = ROOT / "results" / "publication_results.csv"
STATUS_JSON = ROOT / "results" / "publication_status.json"
OUT_DIR = ROOT / "results" / "tables"

QED_ORDER = ["A8", "A6", "F", "A1", "C2", "C3", "C1", "C5", "A2", "C4", "B1", "A3", "A4", "B3", "B2"]
QED_LABELS = {
    "A8": "Decoder coupling (no diversity)",
    "A6": "Decoder coupling (single $\\tau$)",
    "F": "\\textbf{DriftingMol}",
    "A1": "Property-head baseline$^\\dagger$",
    "C2": "LatentMAE-guided drift",
    "C3": "LatentMAE + latent drift",
    "C1": "LatentMAE drift",
    "C5": "LatentMAE-guided + decoder",
    "A2": "Latent-space drift",
    "C4": "LatentMAE + decoder",
    "B1": "Random-feature drift control",
    "A3": "Detached decoder-feature control",
    "A4": "Detached decoder + latent drift",
    "B3": "Stop-gradient decoder control",
    "B2": "Ridge-head baseline$^\\dagger$",
}
MULTI4_ORDER = ["A6", "A8", "F", "G4", "A2", "B1", "NoDrift", "B3"]
MULTI4_LABELS = {
    "A6": "Decoder coupling (single $\\tau$)",
    "A8": "Decoder coupling (no diversity)",
    "F": "DriftingMol",
    "G4": "Layer-balanced decoder coupling",
    "A2": "Latent-space drift",
    "B1": "Random-feature drift control",
    "NoDrift": "No-drift baseline",
    "B3": "Stop-gradient decoder control",
}
SEED_LABELS = {
    "A6": "Decoder coupling (single $\\tau$)",
    "A8": "Decoder coupling (no diversity)",
    "F": "DriftingMol",
    "G4": "Layer-balanced decoder coupling",
}


def read_rows() -> list[dict[str, str]]:
    with RESULTS_CSV.open() as f:
        return list(csv.DictReader(f))


def fnum(value: str | float | None, digits: int = 3) -> str:
    if value in (None, "", "-"):
        return "---"
    try:
        val = float(value)
    except (TypeError, ValueError):
        return str(value)
    if math.isnan(val):
        return "---"
    return f"{val:.{digits}f}"


def fpct(value: str | float | None, digits: int = 1) -> str:
    if value in (None, "", "-"):
        return "---"
    try:
        val = 100.0 * float(value)
    except (TypeError, ValueError):
        return str(value)
    if math.isnan(val):
        return "---"
    return f"{val:.{digits}f}"


def write(path: Path, lines: list[str]) -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n")
    print(f"Wrote {path}")


def qed_table(rows: list[dict[str, str]]) -> None:
    by_variant = {
        r["variant"]: r
        for r in rows
        if r["condition"] == "qed"
        and r["status"].startswith("complete")
        and r["variant"] in QED_ORDER
        and not r.get("manifest_group")
        and r.get("root", "final") in {"final", "final_phi"}
    }
    lines = [
        "% Generated by scripts/export_latex_tables.py",
        "\\begin{tabular}{l c c c c c}",
        "\\toprule",
        "Model / control & $\\alpha$ & $\\rho$ & Slope & U (\\%) & MAE \\\\",
        "\\midrule",
    ]
    for variant in QED_ORDER:
        row = by_variant.get(variant)
        if row is None:
            continue
        alpha = row["alpha"].replace("alpha=", "")
        lines.append(
            f"{QED_LABELS[variant]} & {alpha} & {fnum(row['spearman_rho'])} & "
            f"{fnum(row.get('slope'))} & {fpct(row['uniqueness'])} & {fnum(row['mae'])} \\\\"
        )
        if variant in {"F", "A1", "B1"}:
            lines.append("\\midrule")
    lines += ["\\bottomrule", "\\end{tabular}"]
    write(OUT_DIR / "tab_qed_main.tex", lines)


def multi4_table(rows: list[dict[str, str]]) -> None:
    by_variant = {}
    for r in rows:
        if r["condition"] != "multi4" or not r["status"].startswith("complete"):
            continue
        if r["root"] == "final_v2" or (r["root"] == "multi4" and r["variant"] == "G4"):
            by_variant[r["variant"]] = r
    lines = [
        "% Generated by scripts/export_latex_tables.py",
        "\\begin{tabular}{l c c c c c c c}",
        "\\toprule",
        "Model / control & $\\alpha$ & QED & SA & LogP & MolWt & $\\bar{\\rho}$ & Lowest U \\\\",
        "\\midrule",
    ]
    for variant in MULTI4_ORDER:
        row = by_variant.get(variant)
        if row is None:
            continue
        alpha = row["alpha"].replace("alpha=", "")
        lines.append(
            f"{MULTI4_LABELS[variant]} & {alpha} & {fnum(row['qed_rho'])} & "
            f"{fnum(row['sa_score_rho'])} & {fnum(row['logp_rho'])} & "
            f"{fnum(row['molwt_rho'])} & {fnum(row['avg_spearman_rho'])} & "
            f"{fpct(row.get('min_uniqueness'))} \\\\"
        )
        if variant in {"G4", "B1"}:
            lines.append("\\midrule")
    lines += ["\\bottomrule", "\\end{tabular}"]
    write(OUT_DIR / "tab_multi4_v2.tex", lines)


def qed_seed_table() -> None:
    status = json.loads(STATUS_JSON.read_text()) if STATUS_JSON.exists() else {}
    summaries = status.get("qed_3seed", [])
    lines = [
        "% Generated by scripts/export_latex_tables.py",
        "\\begin{tabular}{l c c c c}",
        "\\toprule",
        "Model / control & Seeds & $n$ & $\\rho$ mean & $\\rho$ 95\\% CI \\\\",
        "\\midrule",
    ]
    for item in summaries:
        ci = item.get("rho_ci95")
        ci_text = "---" if ci is None else fnum(ci)
        label = SEED_LABELS.get(item["variant"], item["variant"])
        lines.append(
            f"{label} & {item.get('seeds', '')} & {item.get('n', 0)} & "
            f"{fnum(item.get('rho_mean'))} & {ci_text} \\\\"
        )
    lines += ["\\bottomrule", "\\end{tabular}"]
    write(OUT_DIR / "tab_qed_3seed.tex", lines)


def main() -> None:
    rows = read_rows()
    qed_table(rows)
    multi4_table(rows)
    qed_seed_table()


if __name__ == "__main__":
    main()
