"""Install the image-2 generated main mechanism figure.

The main conceptual figure is intentionally generated by image-2 as a single raster
asset.  This script does not redraw or overlay diagram elements; it only copies
the approved image-2 output into the manuscript figure path and exports a PDF
backup from the same raster image.
"""
from __future__ import annotations

import os
import shutil
from pathlib import Path

from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
FIG_DIR = ROOT / "docs" / "figures"
SOURCE = FIG_DIR / "image2_assets" / "fig1_main_image2_final.png"
OUT_PNG = FIG_DIR / "fig1_main.png"
OUT_PDF = FIG_DIR / "fig1_main.pdf"


def replace_atomic(src: Path, dst: Path) -> None:
    dst.parent.mkdir(parents=True, exist_ok=True)
    tmp = dst.with_name(f".{dst.stem}.{os.getpid()}.tmp{dst.suffix}")
    try:
        shutil.copy2(src, tmp)
        if not tmp.exists() or tmp.stat().st_size == 0:
            raise RuntimeError(f"failed to write non-empty figure: {tmp}")
        os.replace(tmp, dst)
    finally:
        if tmp.exists():
            tmp.unlink()


def main() -> None:
    if not SOURCE.exists():
        raise FileNotFoundError(f"missing approved image-2 figure: {SOURCE}")
    replace_atomic(SOURCE, OUT_PNG)
    img = Image.open(SOURCE).convert("RGB")
    tmp_pdf = OUT_PDF.with_name(f".{OUT_PDF.stem}.{os.getpid()}.tmp{OUT_PDF.suffix}")
    try:
        img.save(tmp_pdf, "PDF", resolution=300.0)
        os.replace(tmp_pdf, OUT_PDF)
    finally:
        if tmp_pdf.exists():
            tmp_pdf.unlink()
    print(f"Installed image-2 figure: {OUT_PNG.relative_to(ROOT)}")
    print(f"Installed image-2 PDF backup: {OUT_PDF.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
